### ISSUE TITLE
Preliminary Unified App Design

### ISSUE THREAD

**Issue by scottdear** [oceanbuilders/admin-panel#10]
A preliminary design 1-5  document that defines a strategy for switching between roles.  Roles will be contained in the authentication information (we will have to define this further as it's currently based on implicit tokens).   We want to implement something like what is described here

https://medium.com/swlh/server-driven-ui-and-some-herbs-f17f01aa7794

Acceptance Criteria
----------------------
A 2-5 page document that includes a basic diagram that defines the "Atoms" "Molecules" and "Organisms". That will be included in the unified app.

**Comment by margo-pm** [comment]
Closing this issue and archiving this repo.
